# Generated by Django 5.0.14 on 2026-01-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesession',
            name='participant_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codesession',
            name='room_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
