# Generated by Django 5.0.14 on 2026-01-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_codesession_participant_count_codesession_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesession',
            name='creator_username',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
