# Generated by Django 5.0.14 on 2026-01-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_codesession_creator_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesession',
            name='banned_ips',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='codesession',
            name='muted_users',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
